### ISSUE TITLE
Allow setting room subjects

### ISSUE THREAD

**Issue by torfmaster** [TNG/virtual-office#7]
# Description

Rooms can serve several purposes at different times. To explain what is going on in the Room it would be nice to be able to set a room topic (ideally with clickable links) by the users.

# Implementation proposal

Add a clickable field below the room title in the front-end where users can set a title. Maybe this could be restricted to slack users which are (by configuration) set as administrators.

**Comment by greimela** [comment]
Hi @torfmaster,

thanks for the idea and sorry that it took so long to get back to you.

Right now we do not plan to add editing capabilities to the frontend anytime soon, since we do not have a persistence layer in the backend yet.

However, when having a single room that serves different purposes at different times, one could use the `schedule` configuration.
This way a single zoom room can be used in multiple Virtual Office rooms, each with specific start and end times and titles.
